services:
  saasbackend:
    profiles:
      - app
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "${SAASBACKEND_PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    profiles:
      - minio-only
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
