const endpointRegistry = [
  {
    id: "auth",
    title: "Authentication",
    endpoints: [
      {
        id: "register",
        method: "POST",
        path: "/api/auth/register",
        auth: "none",
        bodyExample: { email: "user@example.com", password: "password" },
      },
      {
        id: "login",
        method: "POST",
        path: "/api/auth/login",
        auth: "none",
        bodyExample: { email: "user@example.com", password: "password" },
      },
      {
        id: "refresh",
        method: "POST",
        path: "/api/auth/refresh-token",
        auth: "none",
        bodyExample: { refreshToken: "<refresh_token>" },
      },
      {
        id: "me",
        method: "GET",
        path: "/api/auth/me",
        auth: "jwt",
      },
    ],
  },
  {
    id: "billing",
    title: "Billing",
    endpoints: [
      {
        id: "checkout",
        method: "POST",
        path: "/api/billing/create-checkout-session",
        auth: "jwt",
        bodyExample: { priceId: "price_xxx" },
      },
      {
        id: "portal",
        method: "POST",
        path: "/api/billing/create-portal-session",
        auth: "jwt",
        bodyExample: {},
      },
      {
        id: "reconcile-subscription",
        method: "POST",
        path: "/api/billing/reconcile-subscription",
        auth: "jwt",
        bodyExample: {},
      },
    ],
  },
  {
    id: "admin",
    title: "Admin",
    endpoints: [
      {
        id: "admin-users",
        method: "GET",
        path: "/api/admin/users",
        auth: "basic",
      },
      {
        id: "admin-user",
        method: "GET",
        path: "/api/admin/users/:id",
        auth: "basic",
      },
      {
        id: "admin-update-subscription",
        method: "PUT",
        path: "/api/admin/users/:id/subscription",
        auth: "basic",
        bodyExample: { subscription: "active" },
      },
      {
        id: "admin-reconcile-user",
        method: "POST",
        path: "/api/admin/users/:id/reconcile",
        auth: "basic",
        bodyExample: {},
      },
      {
        id: "admin-generate-token",
        method: "POST",
        path: "/api/admin/generate-token",
        auth: "basic",
        bodyExample: { userId: "<userId>" },
      },
    ],
  },
  {
    id: "stripe-webhooks",
    title: "Stripe Webhooks",
    endpoints: [
      {
        id: "stripe-webhooks-list",
        method: "GET",
        path: "/api/admin/stripe-webhooks",
        auth: "basic",
      },
      {
        id: "stripe-webhook-detail",
        method: "GET",
        path: "/api/admin/stripe-webhooks/:id",
        auth: "basic",
      },
      {
        id: "stripe-webhooks-retry-failed",
        method: "POST",
        path: "/api/admin/stripe-webhooks/retry",
        auth: "basic",
        bodyExample: {},
      },
      {
        id: "stripe-webhook-retry-single",
        method: "POST",
        path: "/api/admin/stripe-webhooks/:id/retry",
        auth: "basic",
        bodyExample: {},
      },
      {
        id: "stripe-webhooks-stats",
        method: "GET",
        path: "/api/admin/stripe-webhooks-stats",
        auth: "basic",
      },
    ],
  },
  {
    id: "notifications-activity",
    title: "Notifications & Activity",
    endpoints: [
      {
        id: "notifications",
        method: "GET",
        path: "/api/notifications",
        auth: "jwt",
      },
      {
        id: "notification-read",
        method: "PUT",
        path: "/api/notifications/:id/read",
        auth: "jwt",
        bodyExample: {},
      },
      {
        id: "activity-log",
        method: "GET",
        path: "/api/activity-log",
        auth: "jwt",
      },
      {
        id: "activity-log-create",
        method: "POST",
        path: "/api/activity-log",
        auth: "jwt",
        bodyExample: { action: "test", metadata: {} },
      },
    ],
  },
  {
    id: "user",
    title: "User Management",
    endpoints: [
      {
        id: "user-profile",
        method: "PUT",
        path: "/api/user/profile",
        auth: "jwt",
        bodyExample: { name: "New Name" },
      },
      {
        id: "user-password",
        method: "PUT",
        path: "/api/user/password",
        auth: "jwt",
        bodyExample: { currentPassword: "old", newPassword: "new" },
      },
      {
        id: "password-reset-request",
        method: "POST",
        path: "/api/user/password-reset-request",
        auth: "none",
        bodyExample: { email: "user@example.com" },
      },
      {
        id: "password-reset-confirm",
        method: "POST",
        path: "/api/user/password-reset-confirm",
        auth: "none",
        bodyExample: { token: "<token>", newPassword: "new" },
      },
      {
        id: "user-account-delete",
        method: "DELETE",
        path: "/api/user/account",
        auth: "jwt",
      },
      {
        id: "user-settings-get",
        method: "GET",
        path: "/api/user/settings",
        auth: "jwt",
      },
      {
        id: "user-settings-update",
        method: "PUT",
        path: "/api/user/settings",
        auth: "jwt",
        bodyExample: { locale: "en" },
      },
    ],
  },
  {
    id: "global-settings",
    title: "Global Settings",
    endpoints: [
      {
        id: "global-settings-public",
        method: "GET",
        path: "/api/admin/settings/public",
        auth: "none",
      },
      {
        id: "global-settings-list",
        method: "GET",
        path: "/api/admin/settings",
        auth: "basic",
      },
      {
        id: "global-setting-get",
        method: "GET",
        path: "/api/admin/settings/:key",
        auth: "basic",
      },
      {
        id: "global-setting-update",
        method: "PUT",
        path: "/api/admin/settings/:key",
        auth: "basic",
        bodyExample: { value: "new-value", isPublic: false },
      },
      {
        id: "global-setting-create",
        method: "POST",
        path: "/api/admin/settings",
        auth: "basic",
        bodyExample: { key: "new.key", value: "value", isPublic: false },
      },
      {
        id: "global-setting-delete",
        method: "DELETE",
        path: "/api/admin/settings/:key",
        auth: "basic",
      },
    ],
  },
  {
    id: "i18n",
    title: "i18n",
    endpoints: [
      {
        id: "i18n-bundle",
        method: "GET",
        path: "/api/i18n/bundle",
        auth: "none",
      },
      {
        id: "admin-i18n-locales",
        method: "GET",
        path: "/api/admin/i18n/locales",
        auth: "basic",
      },
      {
        id: "admin-i18n-locales-create",
        method: "POST",
        path: "/api/admin/i18n/locales",
        auth: "basic",
        bodyExample: { code: "en", name: "English" },
      },
      {
        id: "admin-i18n-locales-update",
        method: "PUT",
        path: "/api/admin/i18n/locales/:code",
        auth: "basic",
        bodyExample: { name: "English" },
      },
      {
        id: "admin-i18n-entries",
        method: "GET",
        path: "/api/admin/i18n/entries",
        auth: "basic",
      },
      {
        id: "admin-i18n-entries-create",
        method: "POST",
        path: "/api/admin/i18n/entries",
        auth: "basic",
        bodyExample: { key: "hello", locale: "en", value: "Hello" },
      },
      {
        id: "admin-i18n-entries-update",
        method: "PUT",
        path: "/api/admin/i18n/entries/:id",
        auth: "basic",
        bodyExample: { value: "Hello" },
      },
      {
        id: "admin-i18n-entries-delete",
        method: "DELETE",
        path: "/api/admin/i18n/entries/:id",
        auth: "basic",
      },
      {
        id: "admin-i18n-ai-preview",
        method: "POST",
        path: "/api/admin/i18n/ai/preview",
        auth: "basic",
        bodyExample: { prompt: "Translate", entries: [] },
      },
      {
        id: "admin-i18n-ai-apply",
        method: "POST",
        path: "/api/admin/i18n/ai/apply",
        auth: "basic",
        bodyExample: { changes: [] },
      },
    ],
  },
  {
    id: "orgs",
    title: "Organizations",
    endpoints: [
      {
        id: "orgs-public",
        method: "GET",
        path: "/api/orgs/public",
        auth: "none",
      },
      {
        id: "orgs-list",
        method: "GET",
        path: "/api/orgs",
        auth: "jwt",
      },
      {
        id: "orgs-create",
        method: "POST",
        path: "/api/orgs",
        auth: "jwt",
        bodyExample: { name: "My Org" },
      },
      {
        id: "org-public",
        method: "GET",
        path: "/api/orgs/:orgId/public",
        auth: "none",
      },
      {
        id: "org-get",
        method: "GET",
        path: "/api/orgs/:orgId",
        auth: "jwt",
      },
      {
        id: "org-update",
        method: "PUT",
        path: "/api/orgs/:orgId",
        auth: "jwt",
        bodyExample: { name: "Updated Org" },
      },
      {
        id: "org-delete",
        method: "DELETE",
        path: "/api/orgs/:orgId",
        auth: "jwt",
      },
      {
        id: "org-join",
        method: "POST",
        path: "/api/orgs/:orgId/join",
        auth: "jwt",
        bodyExample: {},
      },
      {
        id: "org-members",
        method: "GET",
        path: "/api/orgs/:orgId/members",
        auth: "jwt",
      },
      {
        id: "org-add-member",
        method: "POST",
        path: "/api/orgs/:orgId/members",
        auth: "jwt",
        bodyExample: { email: "new.member@example.com", role: "member" },
      },
      {
        id: "org-update-member-role",
        method: "PUT",
        path: "/api/orgs/:orgId/members/:userId/role",
        auth: "jwt",
        bodyExample: { role: "admin" },
      },
      {
        id: "org-remove-member",
        method: "DELETE",
        path: "/api/orgs/:orgId/members/:userId",
        auth: "jwt",
      },
      {
        id: "org-invites",
        method: "GET",
        path: "/api/orgs/:orgId/invites",
        auth: "jwt",
      },
      {
        id: "org-invite-create",
        method: "POST",
        path: "/api/orgs/:orgId/invites",
        auth: "jwt",
        bodyExample: { email: "invitee@example.com", role: "member" },
      },
      {
        id: "org-invite-revoke",
        method: "DELETE",
        path: "/api/orgs/:orgId/invites/:inviteId",
        auth: "jwt",
      },
      {
        id: "orgs-admin-list",
        method: "GET",
        path: "/api/admin/orgs",
        auth: "basic",
      },
      {
        id: "orgs-admin-get",
        method: "GET",
        path: "/api/admin/orgs/:orgId",
        auth: "basic",
      },
      {
        id: "orgs-admin-members-list",
        method: "GET",
        path: "/api/admin/orgs/:orgId/members",
        auth: "basic",
      },
      {
        id: "orgs-admin-member-update",
        method: "PATCH",
        path: "/api/admin/orgs/:orgId/members/:memberId",
        auth: "basic",
        bodyExample: { role: "member" },
      },
      {
        id: "orgs-admin-member-remove",
        method: "DELETE",
        path: "/api/admin/orgs/:orgId/members/:memberId",
        auth: "basic",
      },
      {
        id: "orgs-admin-invites-list",
        method: "GET",
        path: "/api/admin/orgs/:orgId/invites",
        auth: "basic",
      },
      {
        id: "orgs-admin-invites-create",
        method: "POST",
        path: "/api/admin/orgs/:orgId/invites",
        auth: "basic",
        bodyExample: { email: "invitee@example.com", role: "member" },
      },
      {
        id: "orgs-admin-invites-revoke",
        method: "DELETE",
        path: "/api/admin/orgs/:orgId/invites/:inviteId",
        auth: "basic",
      },
      {
        id: "orgs-admin-invites-resend",
        method: "POST",
        path: "/api/admin/orgs/:orgId/invites/:inviteId/resend",
        auth: "basic",
        bodyExample: {},
      },
    ],
  },
  {
    id: "invites",
    title: "Invites",
    endpoints: [
      {
        id: "invite-info",
        method: "GET",
        path: "/api/invites/info",
        auth: "none",
      },
      {
        id: "invite-accept",
        method: "POST",
        path: "/api/invites/accept",
        auth: "none",
        bodyExample: { token: "<invite_token>" },
      },
    ],
  },
  {
    id: "forms",
    title: "Forms",
    endpoints: [
      {
        id: "forms-submit",
        method: "POST",
        path: "/api/forms/submit",
        auth: "none",
        bodyExample: { formId: "contact", fields: { message: "Hello" } },
      },
      {
        id: "forms-admin-list",
        method: "GET",
        path: "/api/admin/forms",
        auth: "basic",
      },
    ],
  },
  {
    id: "waiting-list",
    title: "Waiting List",
    endpoints: [
      {
        id: "waiting-list-subscribe",
        method: "POST",
        path: "/api/waiting-list/subscribe",
        auth: "none",
        bodyExample: { email: "user@example.com" },
      },
      {
        id: "waiting-list-stats",
        method: "GET",
        path: "/api/waiting-list/stats",
        auth: "none",
      },
      {
        id: "waiting-list-admin-list",
        method: "GET",
        path: "/api/admin/waiting-list",
        auth: "basic",
      },
    ],
  },
  {
    id: "metrics",
    title: "Metrics",
    endpoints: [
      {
        id: "metrics-track",
        method: "POST",
        path: "/api/metrics/track",
        auth: "none",
        bodyExample: { event: "test", properties: {} },
      },
      {
        id: "metrics-impact",
        method: "GET",
        path: "/api/metrics/impact",
        auth: "none",
      },
    ],
  },
  {
    id: "feature-flags",
    title: "Feature Flags",
    endpoints: [
      {
        id: "feature-flags-public",
        method: "GET",
        path: "/api/feature-flags/public",
        auth: "none",
      },
      {
        id: "feature-flags-evaluated",
        method: "GET",
        path: "/api/feature-flags",
        auth: "jwt",
      },
      {
        id: "admin-feature-flags-list",
        method: "GET",
        path: "/api/admin/feature-flags",
        auth: "basic",
      },
      {
        id: "admin-feature-flags-get",
        method: "GET",
        path: "/api/admin/feature-flags/:key",
        auth: "basic",
      },
      {
        id: "admin-feature-flags-create",
        method: "POST",
        path: "/api/admin/feature-flags",
        auth: "basic",
        bodyExample: {
          key: "new_checkout",
          description: "Enable new checkout",
          enabled: false,
          rolloutPercentage: 10,
          allowListUserIds: [],
          allowListOrgIds: [],
          denyListUserIds: [],
          denyListOrgIds: [],
          payload: { variant: "A" },
        },
      },
      {
        id: "admin-feature-flags-update",
        method: "PUT",
        path: "/api/admin/feature-flags/:key",
        auth: "basic",
        bodyExample: {
          enabled: true,
          rolloutPercentage: 100,
        },
      },
      {
        id: "admin-feature-flags-delete",
        method: "DELETE",
        path: "/api/admin/feature-flags/:key",
        auth: "basic",
      },
    ],
  },
  {
    id: "assets",
    title: "Assets",
    endpoints: [
      {
        id: "public-assets-get",
        method: "GET",
        path: "/public/assets/:key",
        auth: "none",
      },
      {
        id: "assets-upload",
        method: "POST",
        path: "/api/assets/upload",
        auth: "jwt",
      },
      {
        id: "assets-list",
        method: "GET",
        path: "/api/assets",
        auth: "jwt",
      },
      {
        id: "assets-get",
        method: "GET",
        path: "/api/assets/:id",
        auth: "jwt",
      },
      {
        id: "assets-download",
        method: "GET",
        path: "/api/assets/:id/download",
        auth: "jwt",
      },
      {
        id: "assets-delete",
        method: "DELETE",
        path: "/api/assets/:id",
        auth: "jwt",
      },
      {
        id: "admin-assets-info",
        method: "GET",
        path: "/api/admin/assets/info",
        auth: "basic",
      },
      {
        id: "admin-assets-list",
        method: "GET",
        path: "/api/admin/assets",
        auth: "basic",
      },
      {
        id: "admin-assets-get",
        method: "GET",
        path: "/api/admin/assets/:id",
        auth: "basic",
      },
      {
        id: "admin-assets-upload",
        method: "POST",
        path: "/api/admin/assets/upload",
        auth: "basic",
      },
      {
        id: "admin-assets-update",
        method: "PATCH",
        path: "/api/admin/assets/:id",
        auth: "basic",
        bodyExample: { visibility: "public" },
      },
      {
        id: "admin-assets-delete",
        method: "DELETE",
        path: "/api/admin/assets/:id",
        auth: "basic",
      },
    ],
  },
  {
    id: "admin-users",
    title: "Admin Users",
    endpoints: [
      {
        id: "admin-users-stats",
        method: "GET",
        path: "/api/admin/users/stats",
        auth: "basic",
      },
      {
        id: "admin-users-list",
        method: "GET",
        path: "/api/admin/users",
        auth: "basic",
      },
      {
        id: "admin-users-get",
        method: "GET",
        path: "/api/admin/users/:id",
        auth: "basic",
      },
      {
        id: "admin-users-update",
        method: "PATCH",
        path: "/api/admin/users/:id",
        auth: "basic",
        bodyExample: { name: "Updated Name", role: "user" },
      },
      {
        id: "admin-users-disable",
        method: "POST",
        path: "/api/admin/users/:id/disable",
        auth: "basic",
      },
      {
        id: "admin-users-enable",
        method: "POST",
        path: "/api/admin/users/:id/enable",
        auth: "basic",
      },
    ],
  },
  {
    id: "admin-notifications",
    title: "Admin Notifications",
    endpoints: [
      {
        id: "admin-notifications-stats",
        method: "GET",
        path: "/api/admin/notifications/stats",
        auth: "basic",
      },
      {
        id: "admin-notifications-list",
        method: "GET",
        path: "/api/admin/notifications",
        auth: "basic",
      },
      {
        id: "admin-notifications-send",
        method: "POST",
        path: "/api/admin/notifications/send",
        auth: "basic",
        bodyExample: { userIds: ["userId"], type: "info", title: "Title", message: "Message", channel: "in_app" },
      },
      {
        id: "admin-notifications-broadcast",
        method: "POST",
        path: "/api/admin/notifications/broadcast",
        auth: "basic",
        bodyExample: { type: "info", title: "Title", message: "Message", channel: "both" },
      },
      {
        id: "admin-notifications-delete",
        method: "DELETE",
        path: "/api/admin/notifications/:id",
        auth: "basic",
      },
      {
        id: "admin-notifications-retry-email",
        method: "POST",
        path: "/api/admin/notifications/:id/retry-email",
        auth: "basic",
      },
    ],
  },
  {
    id: "admin-stripe",
    title: "Admin Stripe Pricing",
    endpoints: [
      {
        id: "admin-stripe-status",
        method: "GET",
        path: "/api/admin/stripe/status",
        auth: "basic",
      },
      {
        id: "admin-stripe-catalog-list",
        method: "GET",
        path: "/api/admin/stripe/catalog",
        auth: "basic",
      },
      {
        id: "admin-stripe-catalog-get",
        method: "GET",
        path: "/api/admin/stripe/catalog/:id",
        auth: "basic",
      },
      {
        id: "admin-stripe-catalog-upsert",
        method: "POST",
        path: "/api/admin/stripe/catalog/upsert",
        auth: "basic",
        bodyExample: { productName: "Pro Plan", planKey: "pro_monthly", displayName: "Pro (Monthly)", billingType: "subscription", currency: "usd", unitAmount: 1999, interval: "month" },
      },
      {
        id: "admin-stripe-catalog-import",
        method: "POST",
        path: "/api/admin/stripe/catalog/import",
        auth: "basic",
        bodyExample: { stripePriceId: "price_...", planKey: "pro", displayName: "Pro Plan" },
      },
      {
        id: "admin-stripe-catalog-deactivate",
        method: "POST",
        path: "/api/admin/stripe/catalog/:id/deactivate",
        auth: "basic",
      },
      {
        id: "admin-stripe-catalog-activate",
        method: "POST",
        path: "/api/admin/stripe/catalog/:id/activate",
        auth: "basic",
      },
      {
        id: "admin-stripe-catalog-delete",
        method: "DELETE",
        path: "/api/admin/stripe/catalog/:id",
        auth: "basic",
      },
      {
        id: "admin-stripe-products",
        method: "GET",
        path: "/api/admin/stripe/products",
        auth: "basic",
      },
      {
        id: "admin-stripe-prices",
        method: "GET",
        path: "/api/admin/stripe/prices",
        auth: "basic",
      },
    ],
  },
];

module.exports = endpointRegistry;
