const endpointRegistry = [
  {
    id: "auth",
    title: "Authentication",
    endpoints: [
      {
        id: "register",
        method: "POST",
        path: "/api/auth/register",
        auth: "none",
        bodyExample: { email: "user@example.com", password: "password" },
      },
      {
        id: "login",
        method: "POST",
        path: "/api/auth/login",
        auth: "none",
        bodyExample: { email: "user@example.com", password: "password" },
      },
      {
        id: "refresh",
        method: "POST",
        path: "/api/auth/refresh-token",
        auth: "none",
        bodyExample: { refreshToken: "<refresh_token>" },
      },
      {
        id: "me",
        method: "GET",
        path: "/api/auth/me",
        auth: "jwt",
      },
    ],
  },
  {
    id: "admin-llm",
    title: "AI & LLM Services",
    endpoints: [
      {
        id: "llm-config-get",
        method: "GET",
        path: "/api/admin/llm/config",
        auth: "basic",
      },
      {
        id: "llm-config-save",
        method: "POST",
        path: "/api/admin/llm/config",
        auth: "basic",
        bodyExample: { provider: "openai", apiKey: "sk-...", model: "gpt-4" },
      },
      {
        id: "llm-prompt-test",
        method: "POST",
        path: "/api/admin/llm/prompts/:key/test",
        auth: "basic",
        bodyExample: { inputs: { topic: "SaaS" } },
      },
      {
        id: "llm-audit",
        method: "GET",
        path: "/api/admin/llm/audit",
        auth: "basic",
      },
      {
        id: "llm-costs",
        method: "GET",
        path: "/api/admin/llm/costs",
        auth: "basic",
      },
    ],
  },
  {
    id: "admin-pages",
    title: "Pages (Admin)",
    endpoints: [
      {
        id: "pages-context-block-definitions-list",
        method: "GET",
        path: "/api/admin/pages/context-block-definitions",
        auth: "basic",
      },
      {
        id: "pages-context-block-definitions-create",
        method: "POST",
        path: "/api/admin/pages/context-block-definitions",
        auth: "basic",
        bodyExample: {
          code: "blog-post-by-slug",
          label: "Blog post by slug",
          description: "Used by blog post page",
          type: "context.db_query",
          props: {
            assignTo: "post",
            model: "BlogPost",
            op: "findOne",
            filter: { slug: { $ctx: "params.slug" } },
          },
        },
      },
      {
        id: "pages-context-block-definitions-get",
        method: "GET",
        path: "/api/admin/pages/context-block-definitions/:code",
        auth: "basic",
      },
      {
        id: "pages-context-block-definitions-update",
        method: "PUT",
        path: "/api/admin/pages/context-block-definitions/:code",
        auth: "basic",
        bodyExample: {
          label: "Blog post by slug (updated)",
          description: "Used by blog post page",
          type: "context.db_query",
          props: {
            assignTo: "post",
            model: "BlogPost",
            op: "findOne",
            filter: { slug: { $ctx: "params.slug" } },
          },
        },
      },
      {
        id: "pages-context-block-definitions-delete",
        method: "DELETE",
        path: "/api/admin/pages/context-block-definitions/:code",
        auth: "basic",
      },
      {
        id: "pages-context-blocks-ai-generate",
        method: "POST",
        path: "/api/admin/pages/ai/context-blocks/generate",
        auth: "basic",
        bodyExample: {
          prompt: "Load the published BlogPost for params.slug into vars.post. Add cache 30s.",
          blockType: "context.db_query",
        },
      },
    ],
  },
  {
    id: "ejs-virtual",
    title: "EJS Virtual Codebase",
    endpoints: [
      {
        id: "ejs-files-list",
        method: "GET",
        path: "/api/admin/ejs-virtual/files",
        auth: "basic",
      },
      {
        id: "ejs-file-get",
        method: "GET",
        path: "/api/admin/ejs-virtual/file?path=index.ejs",
        auth: "basic",
      },
      {
        id: "ejs-file-save",
        method: "PUT",
        path: "/api/admin/ejs-virtual/file",
        auth: "basic",
        bodyExample: { path: "index.ejs", content: "<h1>Hello</h1>" },
      },
      {
        id: "ejs-vibe",
        method: "POST",
        path: "/api/admin/ejs-virtual/vibe",
        auth: "basic",
        bodyExample: { prompt: "Make it more professional" },
      },
      {
        id: "ejs-cache-clear",
        method: "POST",
        path: "/api/admin/ejs-virtual/cache/clear",
        auth: "basic",
      },
    ],
  },
  {
    id: "seo-config",
    title: "SEO & OpenGraph",
    endpoints: [
      {
        id: "seo-get",
        method: "GET",
        path: "/api/admin/seo-config",
        auth: "basic",
      },
      {
        id: "seo-update",
        method: "PUT",
        path: "/api/admin/seo-config",
        auth: "basic",
        bodyExample: { defaultTitle: "My SaaS", defaultDescription: "Best SaaS" },
      },
      {
        id: "seo-ai-views",
        method: "GET",
        path: "/api/admin/seo-config/ai/views",
        auth: "basic",
      },
      {
        id: "seo-ai-generate",
        method: "POST",
        path: "/api/admin/seo-config/ai/generate-entry",
        auth: "basic",
        bodyExample: { path: "/home" },
      },
      {
        id: "seo-og-svg-update",
        method: "PUT",
        path: "/api/admin/seo-config/og/svg",
        auth: "basic",
        bodyExample: { svg: "<svg>...</svg>" },
      },
      {
        id: "seo-og-generate-png",
        method: "POST",
        path: "/api/admin/seo-config/og/generate-png",
        auth: "basic",
      },
    ],
  },
  {
    id: "migration",
    title: "System Migration",
    endpoints: [
      {
        id: "migration-envs",
        method: "GET",
        path: "/api/admin/migration/environments",
        auth: "basic",
      },
      {
        id: "migration-models",
        method: "GET",
        path: "/api/admin/migration/models",
        auth: "basic",
      },
      {
        id: "migration-test",
        method: "POST",
        path: "/api/admin/migration/test-connection",
        auth: "basic",
        bodyExample: { targetUrl: "https://peer.example.com", apiKey: "..." },
      },
      {
        id: "migration-run",
        method: "POST",
        path: "/api/admin/migration/run",
        auth: "basic",
        bodyExample: { envKey: "production", models: ["User"] },
      },
    ],
  },
  {
    id: "billing",
    title: "Billing & Stripe",
    endpoints: [
      {
        id: "stripe-status",
        method: "GET",
        path: "/api/admin/stripe/status",
        auth: "basic",
      },
      {
        id: "stripe-catalog",
        method: "GET",
        path: "/api/admin/stripe/catalog",
        auth: "basic",
      },
      {
        id: "stripe-products",
        method: "GET",
        path: "/api/admin/stripe/products",
        auth: "basic",
      },
      {
        id: "billing-checkout",
        method: "POST",
        path: "/api/billing/create-checkout-session",
        auth: "jwt",
        bodyExample: { priceId: "price_xxx" },
      },
    ],
  },
  {
    id: "admin-users",
    title: "User Management (Admin)",
    endpoints: [
      {
        id: "admin-users-stats",
        method: "GET",
        path: "/api/admin/users/stats",
        auth: "basic",
      },
      {
        id: "admin-users-list",
        method: "GET",
        path: "/api/admin/users",
        auth: "basic",
      },
      {
        id: "admin-users-get",
        method: "GET",
        path: "/api/admin/users/:id",
        auth: "basic",
      },
    ],
  },
  {
    id: "global-settings",
    title: "Global Settings",
    endpoints: [
      {
        id: "global-settings-list",
        method: "GET",
        path: "/api/admin/settings",
        auth: "basic",
      },
      {
        id: "global-setting-get",
        method: "GET",
        path: "/api/admin/settings/:key",
        auth: "basic",
      },
      {
        id: "global-setting-update",
        method: "PUT",
        path: "/api/admin/settings/:key",
        auth: "basic",
        bodyExample: { value: "new-value" },
      },
    ],
  },
  {
    id: "errors-audit",
    title: "Errors & Audit",
    endpoints: [
      {
        id: "errors-list",
        method: "GET",
        path: "/api/admin/errors",
        auth: "basic",
      },
      {
        id: "errors-stats",
        method: "GET",
        path: "/api/admin/errors/stats",
        auth: "basic",
      },
      {
        id: "audit-list",
        method: "GET",
        path: "/api/admin/audit",
        auth: "basic",
      },
      {
        id: "audit-actions",
        method: "GET",
        path: "/api/admin/audit/actions",
        auth: "basic",
      },
    ],
  },
  {
    id: "rate-limits",
    title: "Rate Limiter",
    endpoints: [
      {
        id: "rate-limits-list",
        method: "GET",
        path: "/api/admin/rate-limits",
        auth: "basic",
      },
      {
        id: "rate-limits-config-get",
        method: "GET",
        path: "/api/admin/rate-limits/config",
        auth: "basic",
      },
      {
        id: "rate-limits-config-update",
        method: "PUT",
        path: "/api/admin/rate-limits/config",
        auth: "basic",
        bodyExample: { jsonRaw: "{\n  \"version\": 1,\n  \"defaults\": {},\n  \"limiters\": {}\n}" },
      },
      {
        id: "rate-limits-metrics",
        method: "GET",
        path: "/api/admin/rate-limits/metrics?start=2026-01-01T00:00:00.000Z&end=2026-01-02T00:00:00.000Z",
        auth: "basic",
      },
      {
        id: "rate-limits-bulk-enabled",
        method: "POST",
        path: "/api/admin/rate-limits/bulk-enabled",
        auth: "basic",
        bodyExample: { enabled: true, all: true },
      },
      {
        id: "rate-limits-limiter-update",
        method: "PUT",
        path: "/api/admin/rate-limits/globalApiLimiter",
        auth: "basic",
        bodyExample: { override: { enabled: true, mode: "reportOnly", limit: { max: 60, windowMs: 60000 } } },
      },
      {
        id: "rate-limits-limiter-reset",
        method: "POST",
        path: "/api/admin/rate-limits/globalApiLimiter/reset",
        auth: "basic",
      },
    ],
  },
];

module.exports = endpointRegistry;
