const endpointRegistry = [
  {
    id: "auth",
    title: "Authentication",
    endpoints: [
      {
        id: "register",
        method: "POST",
        path: "/api/auth/register",
        auth: "none",
        bodyExample: { email: "user@example.com", password: "password" },
      },
      {
        id: "login",
        method: "POST",
        path: "/api/auth/login",
        auth: "none",
        bodyExample: { email: "user@example.com", password: "password" },
      },
      {
        id: "refresh",
        method: "POST",
        path: "/api/auth/refresh-token",
        auth: "none",
        bodyExample: { refreshToken: "<refresh_token>" },
      },
      {
        id: "me",
        method: "GET",
        path: "/api/auth/me",
        auth: "jwt",
      },
    ],
  },
  {
    id: "billing",
    title: "Billing",
    endpoints: [
      {
        id: "checkout",
        method: "POST",
        path: "/api/billing/create-checkout-session",
        auth: "jwt",
        bodyExample: { priceId: "price_xxx" },
      },
      {
        id: "portal",
        method: "POST",
        path: "/api/billing/create-portal-session",
        auth: "jwt",
        bodyExample: {},
      },
      {
        id: "reconcile-subscription",
        method: "POST",
        path: "/api/billing/reconcile-subscription",
        auth: "jwt",
        bodyExample: {},
      },
    ],
  },
  {
    id: "admin",
    title: "Admin",
    endpoints: [
      {
        id: "admin-users",
        method: "GET",
        path: "/api/admin/users",
        auth: "basic",
      },
      {
        id: "admin-user",
        method: "GET",
        path: "/api/admin/users/:id",
        auth: "basic",
      },
      {
        id: "admin-update-subscription",
        method: "PUT",
        path: "/api/admin/users/:id/subscription",
        auth: "basic",
        bodyExample: { subscription: "active" },
      },
      {
        id: "admin-reconcile-user",
        method: "POST",
        path: "/api/admin/users/:id/reconcile",
        auth: "basic",
        bodyExample: {},
      },
      {
        id: "admin-generate-token",
        method: "POST",
        path: "/api/admin/generate-token",
        auth: "basic",
        bodyExample: { userId: "<userId>" },
      },
    ],
  },
  {
    id: "stripe-webhooks",
    title: "Stripe Webhooks",
    endpoints: [
      {
        id: "stripe-webhooks-list",
        method: "GET",
        path: "/api/admin/stripe-webhooks",
        auth: "basic",
      },
      {
        id: "stripe-webhook-detail",
        method: "GET",
        path: "/api/admin/stripe-webhooks/:id",
        auth: "basic",
      },
      {
        id: "stripe-webhooks-retry-failed",
        method: "POST",
        path: "/api/admin/stripe-webhooks/retry",
        auth: "basic",
        bodyExample: {},
      },
      {
        id: "stripe-webhook-retry-single",
        method: "POST",
        path: "/api/admin/stripe-webhooks/:id/retry",
        auth: "basic",
        bodyExample: {},
      },
      {
        id: "stripe-webhooks-stats",
        method: "GET",
        path: "/api/admin/stripe-webhooks-stats",
        auth: "basic",
      },
    ],
  },
  {
    id: "notifications-activity",
    title: "Notifications & Activity",
    endpoints: [
      {
        id: "notifications",
        method: "GET",
        path: "/api/notifications",
        auth: "jwt",
      },
      {
        id: "notification-read",
        method: "PUT",
        path: "/api/notifications/:id/read",
        auth: "jwt",
        bodyExample: {},
      },
      {
        id: "activity-log",
        method: "GET",
        path: "/api/activity-log",
        auth: "jwt",
      },
      {
        id: "activity-log-create",
        method: "POST",
        path: "/api/activity-log",
        auth: "jwt",
        bodyExample: { action: "test", metadata: {} },
      },
    ],
  },
  {
    id: "user",
    title: "User Management",
    endpoints: [
      {
        id: "user-profile",
        method: "PUT",
        path: "/api/user/profile",
        auth: "jwt",
        bodyExample: { name: "New Name" },
      },
      {
        id: "user-password",
        method: "PUT",
        path: "/api/user/password",
        auth: "jwt",
        bodyExample: { currentPassword: "old", newPassword: "new" },
      },
      {
        id: "password-reset-request",
        method: "POST",
        path: "/api/user/password-reset-request",
        auth: "none",
        bodyExample: { email: "user@example.com" },
      },
      {
        id: "password-reset-confirm",
        method: "POST",
        path: "/api/user/password-reset-confirm",
        auth: "none",
        bodyExample: { token: "<token>", newPassword: "new" },
      },
      {
        id: "user-account-delete",
        method: "DELETE",
        path: "/api/user/account",
        auth: "jwt",
      },
      {
        id: "user-settings-get",
        method: "GET",
        path: "/api/user/settings",
        auth: "jwt",
      },
      {
        id: "user-settings-update",
        method: "PUT",
        path: "/api/user/settings",
        auth: "jwt",
        bodyExample: { locale: "en" },
      },
    ],
  },
  {
    id: "global-settings",
    title: "Global Settings",
    endpoints: [
      {
        id: "global-settings-public",
        method: "GET",
        path: "/api/admin/settings/public",
        auth: "none",
      },
      {
        id: "global-settings-list",
        method: "GET",
        path: "/api/admin/settings",
        auth: "basic",
      },
      {
        id: "global-setting-get",
        method: "GET",
        path: "/api/admin/settings/:key",
        auth: "basic",
      },
      {
        id: "global-setting-update",
        method: "PUT",
        path: "/api/admin/settings/:key",
        auth: "basic",
        bodyExample: { value: "new-value", isPublic: false },
      },
      {
        id: "global-setting-create",
        method: "POST",
        path: "/api/admin/settings",
        auth: "basic",
        bodyExample: { key: "new.key", value: "value", isPublic: false },
      },
      {
        id: "global-setting-delete",
        method: "DELETE",
        path: "/api/admin/settings/:key",
        auth: "basic",
      },
    ],
  },
  {
    id: "i18n",
    title: "i18n",
    endpoints: [
      {
        id: "i18n-bundle",
        method: "GET",
        path: "/api/i18n/bundle",
        auth: "none",
      },
      {
        id: "admin-i18n-locales",
        method: "GET",
        path: "/api/admin/i18n/locales",
        auth: "basic",
      },
      {
        id: "admin-i18n-locales-create",
        method: "POST",
        path: "/api/admin/i18n/locales",
        auth: "basic",
        bodyExample: { code: "en", name: "English" },
      },
      {
        id: "admin-i18n-locales-update",
        method: "PUT",
        path: "/api/admin/i18n/locales/:code",
        auth: "basic",
        bodyExample: { name: "English" },
      },
      {
        id: "admin-i18n-entries",
        method: "GET",
        path: "/api/admin/i18n/entries",
        auth: "basic",
      },
      {
        id: "admin-i18n-entries-create",
        method: "POST",
        path: "/api/admin/i18n/entries",
        auth: "basic",
        bodyExample: { key: "hello", locale: "en", value: "Hello" },
      },
      {
        id: "admin-i18n-entries-update",
        method: "PUT",
        path: "/api/admin/i18n/entries/:id",
        auth: "basic",
        bodyExample: { value: "Hello" },
      },
      {
        id: "admin-i18n-entries-delete",
        method: "DELETE",
        path: "/api/admin/i18n/entries/:id",
        auth: "basic",
      },
      {
        id: "admin-i18n-ai-preview",
        method: "POST",
        path: "/api/admin/i18n/ai/preview",
        auth: "basic",
        bodyExample: { prompt: "Translate", entries: [] },
      },
      {
        id: "admin-i18n-ai-apply",
        method: "POST",
        path: "/api/admin/i18n/ai/apply",
        auth: "basic",
        bodyExample: { changes: [] },
      },
    ],
  },
  {
    id: "orgs",
    title: "Organizations",
    endpoints: [
      {
        id: "orgs-public",
        method: "GET",
        path: "/api/orgs/public",
        auth: "none",
      },
      {
        id: "orgs-list",
        method: "GET",
        path: "/api/orgs",
        auth: "jwt",
      },
      {
        id: "orgs-create",
        method: "POST",
        path: "/api/orgs",
        auth: "jwt",
        bodyExample: { name: "My Org" },
      },
      {
        id: "org-public",
        method: "GET",
        path: "/api/orgs/:orgId/public",
        auth: "none",
      },
      {
        id: "org-get",
        method: "GET",
        path: "/api/orgs/:orgId",
        auth: "jwt",
      },
      {
        id: "org-update",
        method: "PUT",
        path: "/api/orgs/:orgId",
        auth: "jwt",
        bodyExample: { name: "Updated Org" },
      },
      {
        id: "org-delete",
        method: "DELETE",
        path: "/api/orgs/:orgId",
        auth: "jwt",
      },
      {
        id: "org-join",
        method: "POST",
        path: "/api/orgs/:orgId/join",
        auth: "jwt",
        bodyExample: {},
      },
      {
        id: "org-members",
        method: "GET",
        path: "/api/orgs/:orgId/members",
        auth: "jwt",
      },
      {
        id: "org-add-member",
        method: "POST",
        path: "/api/orgs/:orgId/members",
        auth: "jwt",
        bodyExample: { email: "new.member@example.com", role: "member" },
      },
      {
        id: "org-update-member-role",
        method: "PUT",
        path: "/api/orgs/:orgId/members/:userId/role",
        auth: "jwt",
        bodyExample: { role: "admin" },
      },
      {
        id: "org-remove-member",
        method: "DELETE",
        path: "/api/orgs/:orgId/members/:userId",
        auth: "jwt",
      },
      {
        id: "org-invites",
        method: "GET",
        path: "/api/orgs/:orgId/invites",
        auth: "jwt",
      },
      {
        id: "org-invite-create",
        method: "POST",
        path: "/api/orgs/:orgId/invites",
        auth: "jwt",
        bodyExample: { email: "invitee@example.com", role: "member" },
      },
      {
        id: "org-invite-revoke",
        method: "DELETE",
        path: "/api/orgs/:orgId/invites/:inviteId",
        auth: "jwt",
      },
    ],
  },
  {
    id: "invites",
    title: "Invites",
    endpoints: [
      {
        id: "invite-info",
        method: "GET",
        path: "/api/invites/info",
        auth: "none",
      },
      {
        id: "invite-accept",
        method: "POST",
        path: "/api/invites/accept",
        auth: "none",
        bodyExample: { token: "<invite_token>" },
      },
    ],
  },
  {
    id: "forms",
    title: "Forms",
    endpoints: [
      {
        id: "forms-submit",
        method: "POST",
        path: "/api/forms/submit",
        auth: "none",
        bodyExample: { formId: "contact", fields: { message: "Hello" } },
      },
      {
        id: "forms-admin-list",
        method: "GET",
        path: "/api/admin/forms",
        auth: "basic",
      },
    ],
  },
  {
    id: "waiting-list",
    title: "Waiting List",
    endpoints: [
      {
        id: "waiting-list-subscribe",
        method: "POST",
        path: "/api/waiting-list/subscribe",
        auth: "none",
        bodyExample: { email: "user@example.com" },
      },
      {
        id: "waiting-list-stats",
        method: "GET",
        path: "/api/waiting-list/stats",
        auth: "none",
      },
    ],
  },
  {
    id: "metrics",
    title: "Metrics",
    endpoints: [
      {
        id: "metrics-track",
        method: "POST",
        path: "/api/metrics/track",
        auth: "none",
        bodyExample: { event: "test", properties: {} },
      },
      {
        id: "metrics-impact",
        method: "GET",
        path: "/api/metrics/impact",
        auth: "none",
      },
    ],
  },
];

module.exports = endpointRegistry;
